// <auto-generated />
using System;
using LaserTag_API.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaserTag_API.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240927173412_InitAppDbContext")]
    partial class InitAppDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaserTag_API.Core.Models.attribute", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_gun")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.config", b =>
                {
                    b.Property<int>("config_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("config_id"));

                    b.Property<string>("code_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("config_type_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("config_id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.hit_log", b =>
                {
                    b.Property<int>("hit_log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hit_log_id"));

                    b.Property<string>("hit_type_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("round_id")
                        .HasColumnType("int");

                    b.Property<int>("round_id1")
                        .HasColumnType("int");

                    b.Property<int>("source_player_id")
                        .HasColumnType("int");

                    b.Property<int>("target_player_id")
                        .HasColumnType("int");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("hit_log_id");

                    b.HasIndex("round_id1");

                    b.ToTable("Hit_Logs");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.match", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("stage_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.player", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("current_bullet")
                        .HasColumnType("int");

                    b.Property<int>("current_health")
                        .HasColumnType("int");

                    b.Property<string>("mac_gun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mac_vest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.player_attribute", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("attribute_id")
                        .HasColumnType("int");

                    b.Property<int>("attributeid")
                        .HasColumnType("int");

                    b.Property<int>("player_id")
                        .HasColumnType("int");

                    b.Property<int>("playerid")
                        .HasColumnType("int");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("attributeid");

                    b.HasIndex("playerid");

                    b.ToTable("Player_Attributes");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.player_match", b =>
                {
                    b.Property<int>("player_match_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("player_match_id"));

                    b.Property<int>("match_id")
                        .HasColumnType("int");

                    b.Property<int>("matchid")
                        .HasColumnType("int");

                    b.Property<int>("player_id")
                        .HasColumnType("int");

                    b.Property<int>("playerid")
                        .HasColumnType("int");

                    b.Property<int>("team_id")
                        .HasColumnType("int");

                    b.HasKey("player_match_id");

                    b.HasIndex("matchid");

                    b.HasIndex("playerid");

                    b.ToTable("Player_Matches");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.player_upgrade", b =>
                {
                    b.Property<int>("player_upgrade_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("player_upgrade_id"));

                    b.Property<int>("player_match_id")
                        .HasColumnType("int");

                    b.Property<int>("player_match_id1")
                        .HasColumnType("int");

                    b.Property<int>("upgrade_id")
                        .HasColumnType("int");

                    b.Property<int>("upgradeid")
                        .HasColumnType("int");

                    b.HasKey("player_upgrade_id");

                    b.HasIndex("player_match_id1");

                    b.HasIndex("upgradeid");

                    b.ToTable("Player_Upgrades");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.round", b =>
                {
                    b.Property<int>("round_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("round_id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("match_id")
                        .HasColumnType("int");

                    b.Property<string>("round_stage_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("round_id");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.shared_base", b =>
                {
                    b.Property<string>("base_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("base_name1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("base_name2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("base_name3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("base_name4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("base_name5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shared_Groupgroup_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.HasKey("base_id");

                    b.HasIndex("shared_Groupgroup_id");

                    b.ToTable("Shared_Bases");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.shared_group", b =>
                {
                    b.Property<string>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_name1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_name2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_name3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_name4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_name5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("group_id");

                    b.ToTable("Shared_Groups");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.shoot_log", b =>
                {
                    b.Property<int>("shoot_log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shoot_log_id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("player_id")
                        .HasColumnType("int");

                    b.Property<int>("playerid")
                        .HasColumnType("int");

                    b.Property<int>("round_id")
                        .HasColumnType("int");

                    b.Property<int>("round_id1")
                        .HasColumnType("int");

                    b.HasKey("shoot_log_id");

                    b.HasIndex("playerid");

                    b.HasIndex("round_id1");

                    b.ToTable("Shoot_Logs");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.upgrade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.upgrade_attribute", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("attribute_id")
                        .HasColumnType("int");

                    b.Property<int>("attributeid")
                        .HasColumnType("int");

                    b.Property<int>("upgrade_id")
                        .HasColumnType("int");

                    b.Property<int>("upgradeid")
                        .HasColumnType("int");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("attributeid");

                    b.HasIndex("upgradeid");

                    b.ToTable("Upgrade_Attributes");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.hit_log", b =>
                {
                    b.HasOne("LaserTag_API.Core.Models.round", "round")
                        .WithMany()
                        .HasForeignKey("round_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("round");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.player_attribute", b =>
                {
                    b.HasOne("LaserTag_API.Core.Models.attribute", "attribute")
                        .WithMany()
                        .HasForeignKey("attributeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaserTag_API.Core.Models.player", "player")
                        .WithMany()
                        .HasForeignKey("playerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("attribute");

                    b.Navigation("player");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.player_match", b =>
                {
                    b.HasOne("LaserTag_API.Core.Models.match", "match")
                        .WithMany()
                        .HasForeignKey("matchid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaserTag_API.Core.Models.player", "player")
                        .WithMany()
                        .HasForeignKey("playerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("match");

                    b.Navigation("player");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.player_upgrade", b =>
                {
                    b.HasOne("LaserTag_API.Core.Models.player_match", "player_match")
                        .WithMany()
                        .HasForeignKey("player_match_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaserTag_API.Core.Models.upgrade", "upgrade")
                        .WithMany()
                        .HasForeignKey("upgradeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player_match");

                    b.Navigation("upgrade");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.shared_base", b =>
                {
                    b.HasOne("LaserTag_API.Core.Models.shared_group", "shared_Group")
                        .WithMany()
                        .HasForeignKey("shared_Groupgroup_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shared_Group");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.shoot_log", b =>
                {
                    b.HasOne("LaserTag_API.Core.Models.player", "player")
                        .WithMany()
                        .HasForeignKey("playerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaserTag_API.Core.Models.round", "round")
                        .WithMany()
                        .HasForeignKey("round_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player");

                    b.Navigation("round");
                });

            modelBuilder.Entity("LaserTag_API.Core.Models.upgrade_attribute", b =>
                {
                    b.HasOne("LaserTag_API.Core.Models.attribute", "attribute")
                        .WithMany()
                        .HasForeignKey("attributeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaserTag_API.Core.Models.upgrade", "upgrade")
                        .WithMany()
                        .HasForeignKey("upgradeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("attribute");

                    b.Navigation("upgrade");
                });
#pragma warning restore 612, 618
        }
    }
}
