// <auto-generated />
using System;
using LaserTag_API.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaserTag_API.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240924171057_InitAppDbContext")]
    partial class InitAppDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaserTag_API.Core.Models.player", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<decimal?>("balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("current_bullet")
                        .HasColumnType("int");

                    b.Property<int?>("current_health")
                        .HasColumnType("int");

                    b.Property<string>("mac_gun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mac_vest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
